<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/1_Numpy_Array_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **List**

In [1]:
# List is used to store a collection of items
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [2]:
list2 = [1, "Hello", 3.14, True, 5]
list2

[1, 'Hello', 3.14, True, 5]

### **Creating Numpy Arrays**

In [3]:
import numpy as np

In [4]:
a1 = np.arange(10) # create a range from 0 to 9

print(a1)
print("Shape of Array a1", a1.shape)

[0 1 2 3 4 5 6 7 8 9]
Shape of Array a1 (10,)


In [5]:
a2 = np.arange(0,10,2) # create a range from 0 to 9, step 2

print(a2)
print("Shape of Array a2", a2.shape)

[0 2 4 6 8]
Shape of Array a2 (5,)


In [6]:
a21 = np.arange(0,10,3) # create a range from 0 to 9, step 3

print(a21)
print("Shape of Array a21", a21.shape)

[0 3 6 9]
Shape of Array a21 (4,)


#### **np.zeros**

In [7]:
a3 = np.zeros(5) # create an array with all 0's

print(a3)
print("Shape of Array a3", a3.shape)

[0. 0. 0. 0. 0.]
Shape of Array a3 (5,)


In [9]:
a4 = np.zeros((2,3)) # array of rank 2 with all 0s; 2 rows & 3 columns

print(a4)
print("Shape of Array a4", a4.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
Shape of Array a4 (2, 3)


In [10]:
a5 = np.full((2,3),8) # array of rank 2 with all 0s;

print(a5)
print("Shape of Array a5", a5.shape)

[[8 8 8]
 [8 8 8]]
Shape of Array a5 (2, 3)


#### **identity matrix**

 - the eye function returns a 2d array with ones on the diagonal and zeros elsewhere

In [11]:
a6 = np.eye(4) # 4x4 identity matrix

print(a6)
print("Shape of Array a6", a6.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape of Array a6 (4, 4)


#### **random numbers**

In [12]:
a7 = np.random.random((2,4))  # rank 2 array (2 rows 4 columns) with random values

print(a7)
print("Shape of Array a7", a7.shape)

[[0.44434986 0.81436765 0.24160902 0.63027532]
 [0.8630283  0.19378075 0.55456315 0.65698898]]
Shape of Array a7 (2, 4)


#### **Array from list**

In [13]:
list1 = [1,2,3,4,5]
print(list1)

r1 = np.array(list1)
print(r1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
