<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/2_Numpy_Array_Dimension's_CSEPthshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* [1) Numpy Array creation](#1)

   * [1.1) List](#1.1)

   * [1.2) Tuple](#1.2)

   * [1.3) Set](#1.3)

   * [1.4) Dictionary](#1.4)

* [2) Dimensions in Arrays](#2)

   * [2.1) 0-D Arrays (or) Scalars](#2.1)

   * [2.2) 1-D Arrays](#2.2)

   * [2.3) 2-D Arrays](#2.3)

   * [2.4) 3-D Arrays](#2.4)

* [3) Check number of dimensions](#3)

* [4) Higher Dimensional Arrays](#4)

- NumPy is used to work with arrays

- The array object in NumPy is called ndarray

- We can create a NumPy ndarray object by using the array() function


------------------

In [19]:
import numpy as np

### **1) NumPy Array Creation**


- **type():** This built-in python function tells the type of the object passed to it.

- To create an **ndarray**, we can pass a **list, tuple** or any array-like object into the array() method and it will be converted into an ndarray.


##### **1.1) List**

In [3]:
list = [1,2,3,4,5]

arr = np.array(list)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [11,12,13,14,15]

arr = np.array([list1, list2, list3])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


##### **1.2) tuple**

In [5]:
tuple = (1,2,3,4,5)

arr = np.array(tuple)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


##### **1.3) set**

In [6]:
set = {1,2,3,4,5}

arr = np.array(set)
print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


##### **1.4) dictionary**

In [7]:
dic = {"Name":"Nirmal", "Surname":"Gaud"}

arr = np.array(dic)
print(arr)
print(type(arr))

{'Name': 'Nirmal', 'Surname': 'Gaud'}
<class 'numpy.ndarray'>


### **2) Dimensions in Arrays**

- A dimension in arrays is one level of array depth (nested arrays)

- Nested array are arrays that have arrays as their elements

##### **2.1) 0-D Arrays (or) Scalars**

- 0-D arrays or Scalars, are the elements in an array. Each value in an array is a 0-D array.

- Create a 0-D array with value 10

In [8]:
arr = np.array(10)
print(arr)
print(type(arr))

10
<class 'numpy.ndarray'>


##### **2.2) 1-D Arrays:**

- An array that has 0-D arrays as its elements is called unidimensional or 1-D array. There are the most common and basic arrays.

- create a 1-D array containing the values 6,7,8,9,10

In [9]:
arr = np.array(dic)
print(arr)
print(type(arr))

[ 6  7  8  9 10]
<class 'numpy.ndarray'>


##### **2.3) 2-D Arrays:**

- An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors. NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

- create a 2-D array containing two arrays with the values 1,2,3 and 4,5,5

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [12]:
set1 = {1,2}
set2 = {3,4}

arr = np.array([set1, set2])
print(arr)
print(type(arr))

[{1, 2} {3, 4}]
<class 'numpy.ndarray'>


##### **2.4) 3-D Arrays:**

- An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.

- Create a 3-D array with two 2-D arrays both containing two arrays with the values 1,2,3 and 4,5,6.

In [13]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(type(arr))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


In [14]:
list1 = [1,2,3]
list2 = [4,5,6]

arr = np.array([[list1, list2]])
print(arr)
print(type(arr))

[[[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


#### **3) Check number of dimensions**

- **Numpy arrays** provides the **ndim** attribute that returns an integer that tells us **how many dimensions** the arrays have.

In [15]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print("Dimension of a is:", a.ndim)
print("Dimension of b is:", b.ndim)
print("Dimension of c is:", c.ndim)
print("Dimension of d is:", d.ndim)

Dimension of a is: 0
Dimension of b is: 1
Dimension of c is: 2
Dimension of d is: 3


#### **4) Higher Dimensional Arrays**

- An array can have any number of dimensions. When the array is created you can define the **number of dimensions** by using the **ndmin** argument. Create an array with 5 dimensions and verify that it has 5 dimensions.

In [17]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("number of dimensions:", arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [18]:
arr = np.array([[1,2,3,4],[5,6,7,8]], ndmin=6)
print(arr)
print("number of dimensions:", arr.ndim)

[[[[[[1 2 3 4]
     [5 6 7 8]]]]]]
number of dimensions: 6


### **Reference**

- https://www.youtube.com/watch?v=nCGvTmiRla0&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=2 ---> Numpy Array Dimension's