<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/4_NumPy_Array_Slicing_CSCPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### **Slicing 1d Array**

- Slicing in NumPy array is similar to how it works with a python list.

In [2]:
list = [1,2,3,4,5]
arr = list[1:3]
print(arr)

[2, 3]


In [3]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])
print("The NumPy Array is:")
print(arr)
arr1 = arr[1:3, :3]  # row 1 to 3 (not inclusive) and first 3 columns
print("The sliced NumPy Array is:")
print(arr1)

The NumPy Array is:
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The sliced NumPy Array is:
[[4 5 6]
 [9 8 7]]


- Slicing in python means taking elements from one given index to another given index

 - we pass slice instead of index like this: [start:end]

 - we can also define the step, like this:[start:end:step]

 - If we don't pass start its considered 0.

 - If we don't pass end it's considered length of array in that dimension

 - If we don't pass step it's considered 1.

In [4]:
# Slice elements from index 1 to index 5 from the following array
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [5]:
# Slice elements from index 4 to the end of the array
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [6]:
# Slice elements from the begining to index 4(not included)
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


#### **Negative Slicing:** use minus operator to refer to an index from the end.

In [7]:
# slice from the index 3 from the end to index 1 from the end
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


#### Use the step value to determine the step of the slicing

In [8]:
# Return every other element from index 1 to index 5
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [9]:
# Return every other element from the entire array
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


### **Slicing 2d Array**

In [10]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 2])

[3 8]


In [13]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


#### **NumPy Slice as a reference:** It is noteworthy that the results of a NumPy slice is a reference and not a copy of the original array

In [18]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])
print("The NumPy Array is:")
print(arr)
arr1 = arr[1:, 2:]    # row 1 onwards and column 2 onwards, arr 1 is now pointing to a subset of array
print("The sliced NumPy Array is:")
print(arr1)

The NumPy Array is:
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The sliced NumPy Array is:
[[6 7 8]
 [7 6 5]]


In [19]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])
print("The NumPy Array is:")
print(arr)
arr1 = arr[1:, 2:]    # row 1 onwards and column 2 onwards, arr 1 is now pointing to a subset of array
print("The sliced NumPy Array is:")
print(arr1)
arr1[0,2]=88
print("Updated NumPy Array:")
print(arr)

The NumPy Array is:
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The sliced NumPy Array is:
[[6 7 8]
 [7 6 5]]
Updated NumPy Array:
[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]


In [20]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])
print("The NumPy Array is:")
print(arr)
arr1 = arr[2:, :]    # row 2 onwards and all columns
print("The sliced NumPy Array is:")
print(arr1)
print("The shape of Sliced NumPy Array is:")
print(arr1.shape)

The NumPy Array is:
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The sliced NumPy Array is:
[[9 8 7 6 5]]
The shape of Sliced NumPy Array is:
(1, 5)


In [21]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])
print("The NumPy Array is:")
print(arr)
arr1 = arr[2, :]    # row 2 onwards and all columns
print("The sliced NumPy Array is:")
print(arr1)
print("The shape of Sliced NumPy Array is:")
print(arr1.shape)

The NumPy Array is:
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The sliced NumPy Array is:
[9 8 7 6 5]
The shape of Sliced NumPy Array is:
(5,)


### **Reference**

- https://www.youtube.com/watch?v=qZnphlnTPIg&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=4