<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day12_NumPy_Joining_Array_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- np.concatenate

- np.stack

- np.hstack

- np.vstack

- np.dstack

-----------------

### **Joining Numpy Arrays**

- Joining means putting contents of two or more arrays in a single array. In SQL we join tables based on a key, wheres in NumPy we join arrays by axes. We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

#### **Join two arrays**

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))
print('The concatenated array is:', arr)

The concatenated array is: [1 2 3 4 5 6]


#### **Join 2-D arrays along rows (axis=1)**

In [6]:
arr1 = np.array([[1,2],[3,4]])
print(arr1)
arr2 = np.array([[5,6],[7,8]])
print(arr2)
arr = np.concatenate((arr1, arr2), axis=0)
print('The concatenated array along rows is:')
print(arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
The concatenated array along rows is:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
arr1 = np.array([[1,2],[3,4]])
print(arr1)
arr2 = np.array([[5,6],[7,8]])
print(arr2)
arr = np.concatenate((arr1, arr2), axis=1)
print('The concatenated array along rows is:')
print(arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
The concatenated array along rows is:
[[1 2 5 6]
 [3 4 7 8]]


#### **Joining Arrays Using Stack Function** 

- **Stacking is same as concatenation:** the only difference is that **stacking is done along a new axis.**

- We can concatenate **two 1-D arrays** along the **second axis** which would result in putting them one over the other, that is stacking.

- We pass a sequence of arrays that we want to join to the **stack()** method along with the axis. If axis is not explicitly passed it is taken as 0.

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis=0)
print('The stacked array is:')
print(arr)

The stacked array is:
[[1 2 3]
 [4 5 6]]


In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis=1)
print('The stacked array is:')
print(arr)

The stacked array is:
[[1 4]
 [2 5]
 [3 6]]


##### **Stacking along rows**

- NumPy provides a helper function **hstack()** to stack along **rows**

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.hstack((arr1, arr2))
print('The stacked array along row is:')
print(arr)

The stacked array along row is:
[1 2 3 4 5 6]


##### **Stacking Along Columns**

- NumPy provides a helper function **vstack()** to stack along **columns**

In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.vstack((arr1, arr2))
print('The stacked array along column is:')
print(arr)

The stacked array along column is:
[[1 2 3]
 [4 5 6]]


##### **Stacking Along Height (Depth)**

- NumPy provides a helper function **dstack()** to stack along **height**, which is same as depth.

In [12]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.dstack((arr1, arr2))
print('The stacked array along height is:')
print(arr)

The stacked array along height is:
[[[1 4]
  [2 5]
  [3 6]]]


### **Reference**

- https://www.youtube.com/watch?v=LDM7QxVa_WE&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=12