<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day14_Searching_and_Filtering_in_NumPy_Array_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **1) Searching Arrays**

- We can search an array for a certain value, and return the indexes that get a match. To search an array, use the **where()** method.

##### **Find the indexes where value is 4**

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


##### **Find the indexes where values are even**

In [3]:
arr = np.array([1,2,3,4,5,6,7,8])

x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


##### **Find the indexes where values are odd**

In [4]:
arr = np.array([1,2,3,4,5,6,7,8])

x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


### **2) Search Sorted**

- There is a method called **searchsorted()** which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order. The **searchsorted()** method is assumed to be used on sorted arrays.

##### **Find the indexes where the value 7 should be inserted**

In [5]:
arr = np.array([6,7,8,9])

x = np.searchsorted(arr, 7)
print(x)

1


#### **2.1) Search from the Right Side**

- By default the left most index is returned, but we can give side='right' to return the right most index instead.

##### **Find the indexes where the value 7 should be inserted, starting from right**

In [6]:
arr = np.array([6,7,8,9])

x = np.searchsorted(arr, 7, side='right')
print(x)

2


#### **2.2) Multiple Values**

- To search for more than one value, use an array with the specified values.

##### **Find the indexes where the values 2,4 and 6 should be inserted**

In [7]:
arr = np.array([1,3,5,7])

x = np.searchsorted(arr, [2,4,6])
print(x)

[1 2 3]


- The return value is an array [1,2,3] containing the three indexes where 2,4,6 would be inserted in the original array to maintain the order.

### **3) NumPy Filter Array**

- Getting some elements out of an existing array and creating a new array out of them is called filtering. In NumPy, we filter an array a boolean index list.

- A boolean index list is a list of booleans corresponding to indexes in the array.

- If the value at an index is True that element is contained in the filtered array.

- If the value at that index is False that element is excluded from the filtered copy.

**create an array from the elements on index 0 and 2**

In [8]:
arr = np.array([41,42,43,44])

x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


#### **Creating the Filter Array**

- In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

##### **Create a filter array that will return only values higher than 42** 

In [9]:
arr = np.array([41,42,43,44])

filter_arr = []

for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


##### **Create a filter array that will return only even elements from the original array**

In [10]:
arr = np.array([1,2,3,4,5,6,7])

filter_arr = []

for element in arr:
  if element %2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


#### **Creating Filter Directly From Array**

- The above example is a quite common task in NumPy and NumPy provides a nice way to tackle it. We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

##### **Create a filter array that will return only values higher than 42**

In [11]:
arr = np.array([41,42,43,44])

filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


##### **Create a filter array that will return only even elements from the original array**

In [12]:
arr = np.array([1,2,3,4,5,6,7])

filter_arr = arr %2 == 0
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


### **Reference**

- https://www.youtube.com/watch?v=FWhWg_NF-q4&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=14