<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day15_Random_Numbers_in_NumPy_Pathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **What is a Random Number?**

- Random number does NOT mean a different number every time. Random means something that cannot be predicted logically.

#### **Pseudo Random and True Random**

- Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

- If there is aprogram to generate random number it can be predicted, thus it is not truely random.

- **Random numbers** generated through a generation algorithm are called **pseudo random**.

#### **Can we make truly Random Numbers?**

- Yes. In order to generate a truely random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on networks etc. We do not need truly random numbers, unless it is related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels) 

#### **1) Generate Random Number**

- NumPy offers the random module to work with random numbers.

In [2]:
import numpy as np
from numpy import random

In [3]:
# Generate a random integer from 0 to 100

x = random.randint(100)
print(x)

17


In [4]:
# Generate a random integer from 0 to 100

x = random.randint(100)
print(x)

57


#### **2) Generate Random Float**

- The random modules **rand()** method returns a random float between 0 and 1.

In [5]:
# Generate a random float from 0 to 1

x = random.rand()
print(x)

0.346989078719523


In [6]:
# Generate a random float from 0 to 1

x = random.rand()
print(x)

0.11345368340579698


#### **3) Generate Random Array**

- In NumPy we work with arrays, and we can use the two methods from the above examples to make random arrays.

##### **3.1) Integers**
- The **randint()** method takes a **size** parameter where we can specify the **shape** of an array.

In [7]:
# Generate a 1-D array containing 5 random integers from 0 to 100

x = random.randint(100, size=(5))
print(x)

[93 14 48 18 95]


In [8]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

x = random.randint(100, size=(3,5))  # 3 rows; 5 elements in each row
print(x)

[[72 81 87 49 25]
 [44 35 54 25 29]
 [55 34 52 93 40]]


##### **3.2) Floats**

- The **rand()** method also allows you to specify the **shape** of the array

In [9]:
# Generate a 1-D array containing 5 random floats

x = random.rand(5)
print(x)

[0.32059086 0.41812302 0.38287109 0.44711067 0.6945388 ]


In [10]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers

x = random.rand(3,5)
print(x)

[[0.34583299 0.39359908 0.7500127  0.57343864 0.92507456]
 [0.43850668 0.9927156  0.63948791 0.8562448  0.41309068]
 [0.98582194 0.13246335 0.4678971  0.77084353 0.79965953]]


#### **4) Generate Random Number from Array**

- The **choice()** method allows you to generate a random value based on an array of values. 

- The choice() method takes an array as a parameter and randomly returns one of the values

In [11]:
# Return one of the values in an array

x = random.choice([3,5,7,9])
print(x)

5


- The **choice()** method also allows you to return an **array of values**. Add a **size** parameter to specify the **shape** of the array.

In [12]:
# Generate a 2-D array that consists of the values in the array parameter (3,5,7 and 9)

x = random.choice([3,5,7,9], size=(3,5))
print(x)

[[5 5 7 3 3]
 [9 5 7 3 3]
 [9 3 9 5 9]]


### **Reference**

- https://www.youtube.com/watch?v=BPQKwsrv2Rs&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=15