<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day10_NumPy_Array_Copy%2C_View%2C_Shape_and_Reshape_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#### **NumPy Array Copy Vs View**

- The difference b/n copy and view

 - The main difference b/n copy and view of an array is that the copy is a new array, and the view is just a view of the original array.

 - The copy ownns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

 - The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

#### **COPY EXAMPLE**
- Make a copy, change the original array and display both arrays

In [2]:
arr = np.array([1,2,3,4,5])
arr1 = arr.copy()
arr[0] = 42
print(arr)
print(arr1)

[42  2  3  4  5]
[1 2 3 4 5]


#### **VIEW EXAMPLE**

- Make a view, change the original array, and display both arrays.

In [3]:
arr = np.array([1,2,3,4,5])
arr1 = arr.view()
arr[0] = 42
print(arr)
print(arr1)

[42  2  3  4  5]
[42  2  3  4  5]


- **Make changes in the view** 
 - Make a view, change the view and display both arrays.

In [4]:
arr = np.array([1,2,3,4,5])
arr1 = arr.view()
arr[0] = 31
print(arr)
print(arr1)

[31  2  3  4  5]
[31  2  3  4  5]


#### **Check if Array owns its data**
- As mentioned above, copies own the data and a view does not own the data, but how can we check this?

- Every NumPy array has the attribute base that returns none if the array owns the data. Otherwise the base attribute refers to the original object.

##### **Print the value of the base attribute to check if an array owns it's data or not**

In [5]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


#### **NumPy array shape**

**Shape of an array:** The shape of an array is the number of elements in each dimension

**Get the shape of an array:** Numpy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


- Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4.

In [7]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("shape of array:", arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


##### **What does the shape tuple represent?**

- An integer at every index tells about the number of elements the corresponding dimension has. In the example above at index -4 we have value 4, so we can say that 5th(4+1th) dimension has 4 elements

#### **NumPy array Reshaping**

- Reshaping means changing the shape of an array. The shape of an array is the number of elements in each dimension. By reshaping we can add or remove dimensions change number of elements in each dimension.

- **Reshape from 1-D to 2-D**

 - Convert the following 1-D array with 12 elements into a 2-D array. The outermost dimension will have 4 arrays, each with 3 elements.

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


 - **Reshape from 1-D to 3-D**

  - Convert the following 1-D array with 12 elements into a 3-D array. The outermost dimension will have 2 arrays that contain 3 arrays, each with 2 elements.

In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### **Can we reshape into any shape?**

- Yes, as long as the elements required for reshaping are equal in both shapes. We can reshape an 8 elements 1 D array into 4 elements in two rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3X3=9 elements.

- Converting 1 D array with 8 elements to a 2 D array with 3 elements in each dimension

In [10]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(3,3)
print(newarr)

ValueError: ignored

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr = arr.reshape(3,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### **Returns Copy or View?**
- Check if returned array is a copy or a view

In [13]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


#### **Unknown Dimension**

- We are allowed to have one "unknown" dimension. Meaning that we do not have to specify an exact number for one of the dimensions in the reshape method. Pass -1 as the value, and numpy will calculate this number for you.

- **Convert 1 D array with 8 elements to 3 D array with 2x2 elements.**

In [14]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


- we can not pass -1 to more than one dimension

#### **Flattening the Arrays**

 - Flattening arrays means **converting a multidimensional array** into a **1-D array**. We can use **reshape(-1)** to do this.

- **Convert the array into 1-D array**

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
newarr = arr.reshape(-1)
print(newarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


#### **Reference**

- https://www.youtube.com/watch?v=CAWUxL2Cw_I&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=10