<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day11_NumPy_Array_Iteration_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

- Iteration means going through elements one by one. As we deal with multidimensional arrays in numpy, we can do this using basic for loop of python. If we iterate on a 1-D array it will go through each element one by one.

##### **Iterate on the elements of the 1-D array**

In [2]:
arr = np.array([1,2,3])

for x in arr:
  print(x)

1
2
3


##### **Iterating 2-D array**

- In a 2-D array, it will go through all the rows

- Iterate on the elements of the 2-D array

In [3]:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


##### **Iterating n-D array**

- If we iterate on a n-D array it will go through n-1th dimension one by one. To return the actual values, the scalers, we have to iterate the arrays in each dimesion.

In [5]:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


##### **Iterating 3-D array**

- In a 3-D array it will go through all the 2-D arrays

- Iterate on the elements of the 3-D array

In [6]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


- To return the actual values, the scalars, we have to iterate the arrays in each dimension.

In [7]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### **Iterating Arrays Using nditer()**

- The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration.

##### **Iterating on each scalar element**

- In basic for loops, iterating through each scalar of an array we need to use n for loopswhich can be difficult to write for arrays with very high dimensionality.

In [9]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### **Iterating Array with Different Data Types**

- we can use **op_dtypes** argument and pass it the expected data type to **change** the data type of elements while iterating.

- NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in **nditer()** we pass **flags=["buffered"]**.

In [10]:
arr = np.array([1,2,3])

for x in np.nditer(arr, flags=["buffered"], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


##### **Iterating with Different Step Size**

- Iterate through every scalar element of the 2D array skipping 1 element

In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[:, ::1]):
  print(x)

1
2
3
4
5
6
7
8


In [13]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [12]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[:, ::3]):
  print(x)

1
4
5
8


In [14]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr[1:, ::2]):
  print(x)

5
7


#### **Enumerated iteration Using ndenumerate()**

- Enumeration means mentioning sequence number of somethings one by one

- Sometimes we require cooresponding index of the element while iterating, the ndenumerate() method can be used for those use cases.

##### **Enumerate 1-D arrays**

In [15]:
arr = np.array([1,2,3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


##### **Enumerate 2-D arrays**

In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [18]:
arr = np.array([[[1,2,3]]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3


### **Reference**

- https://www.youtube.com/watch?v=183p6xeSShA&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=12