<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day23_Simple_Arithmetic_and_Rounding_Decimals_in_NumPy_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **Simple Arithmatic**

- We could use **arithmatic operators +-/*** directly between numpy arrays. But an extension to it we have functions that can take any array-like objects e.g. lists, tuples etc and perform arithmatic conditionally.

**Arithmatic Conditionally:** means that we can define conditions where the arithmatic operation should happen.

#### **1) power()**

  - The power functions rises the values from the first array to the power of the values of the second array and return the results in a new array.

In [1]:
import numpy as np

In [3]:
arr1 = np.array([10, 20, 30, 4, 5, 6])
arr2 = np.array([3, 5, 6, 8, 2, 3])

newarr = np.power(arr1, arr2)
print(newarr)

[     1000   3200000 729000000     65536        25       216]


#### **2) Remainder**

- Both the **mod() and the remainder()** functions return the remainder of the values in the first array corresponding to the values in the second array and return the results in a new array.

In [5]:
# Return the remainders

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


- we get the same result when using the remainder() function

In [6]:
# Return the remainders

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


#### **3) Quotient and Mod**

- The **divmod()** function return **both the quotient and the mod**.

- The return values is **two arrays**, the **first array** contains the **quotient** and the **second array** contains the **mod**.

In [7]:
# Return the quotient and mod

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)
print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


#### **4) Absolute Values**

- Both the **absolute() and abs()** functions **do the same** absolute operation element-wise but we should use **absolute()** to avoid confusion with python's inbuilt **math.abs()**

In [8]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
print(newarr)

[1 2 1 2 3 4]


#### **Rounding Decimals**

There are primarily five ways of rounding off decimals in NumPy

 - Truncation

 - fix

 - rounding

 - floor

 - ceil

##### **a) Truncation**

- **Remove the decimals** and return the float number closest to **zero**. Use the **trunc() and fix()** functions.

In [9]:
# Truncate elements of following array

arr = np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [10]:
# fix elements of following array

arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


##### **b) Rounding**

- The around() function increments preceding digit or decimal by 1

- Example round off to 1 decimal point, 3.16666 is 3.2

In [11]:
# Round off 3.1666 to 2 decimal places

arr = np.around(3.1666, 2)
print(arr)

3.17


##### **c) Floor**

- The **floor()** function rounds off decimal to nearest lower integer. E.g floor of 3.166 is 3

In [12]:
# Floor the elements of following array

arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


- The **floor()** function returns floats, unlike the **trunc()** function who returns integers

##### **d) ceil**

- The **ceil()** function rounds off decimal to **nearest upper integer**. E.g. ceil of **3.166 is 4**.

In [13]:
# Ceil the elements of following array

arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]


#### **Reference**

- https://www.youtube.com/watch?v=15UW-DfuVbs&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=24