<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day28_NumPy_Set_Operations_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **What is a set?**

- A **set** in mathematics is a collection of **unique elements**

- **Sets** are used for operations involving frequent **intersection, union and difference operations**.

#### **1) Create sets in NumPy**

- We can use NumPy's **unique()** method to find **unique elements from any array**. E.g. create a set array, but remember that the set arrays should only be 1-D arrays. 

In [1]:
import numpy as np

In [2]:
# Convert following array with repeated elements to a set

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


#### **2) Finding Union**

- To find the **unique** values of **two arrays**, use the **union1d()** method.

In [4]:
# Find union of the following two set arrays

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6]


#### **3) Finding Intersection**

- To find only the values that are **present in both arrays**, use the **intersect1d()** method.

In [5]:
# Find intersection of the following two set arrays

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

[3 4]


**Note:**
- the **intersect1d()** method takes an optional argument **assume_unique**, which if set to **True** can **speed up computation**.

- It should always be set to **True** when **dealing with sets**.

#### **4) Finding Difference**

- To find only the values in the **first set that is NOT present in the seconds set** use the **setdiff1d()** method.

In [6]:
# Find the difference of the set1 from set2

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.setdiff1d(arr1, arr2, assume_unique=True)
print(newarr)

[1 2]


**Note:** the **setdiff1d()** method takes an optional argument **assume_unique**, which if set to True can speed up computation. It should always be set to True when dealing with sets.

#### **5) Finding Symmetric Difference**

- To find **only** the values that are **NOT** present in **BOTH sets**, use the **setxor1d()** method 

In [7]:
# Find the symmetric difference of the set1 and set2

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.setxor1d(arr1, arr2, assume_unique=True)
print(newarr)

[1 2 5 6]


**Note:** the **setxor1d()** method takes an optional argument **assume_unique**, which if set to True can speed up computation. It should always be set to True when dealing with sets.

#### **Reference**

- https://www.youtube.com/watch?v=tSkduMieU58&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=28