<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day60_Principal_Component_Analysis_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
A = np.matrix([[1,2,3,4],
               [5,5,6,7],
               [1,4,2,3],
               [5,3,2,3],
               [8,1,2,2]])

In [3]:
df = pd.DataFrame(A, columns=['f1', 'f2', 'f3', 'f4'])
df

f1  f2  f3  f4
0   1   2   3   4
1   5   5   6   7
2   1   4   2   3
3   5   3   2   3
4   8   1   2   2

In [4]:
df_std = (df-df.mean()) / (df.std())
df_std

f1        f2        f3        f4
0 -1.000000 -0.632456  0.000000  0.103975
1  0.333333  1.264911  1.732051  1.663601
2 -1.000000  0.632456 -0.577350 -0.415900
3  0.333333  0.000000 -0.577350 -0.415900
4  1.333333 -1.264911 -0.577350 -0.935775

### **Without Sklearn**

In [5]:
df_cov = np.cov(df_std.T, bias=1)
df_cov

array([[ 0.8       , -0.25298221,  0.03849002, -0.10397505],
       [-0.25298221,  0.8       ,  0.51120772,  0.59183635],
       [ 0.03849002,  0.51120772,  0.8       ,  0.78039029],
       [-0.10397505,  0.59183635,  0.78039029,  0.8       ]])

In [7]:
cov_mat = np.cov(df_std.T, bias=0)
cov_mat

array([[ 1.        , -0.31622777,  0.04811252, -0.12996881],
       [-0.31622777,  1.        ,  0.63900965,  0.73979544],
       [ 0.04811252,  0.63900965,  1.        ,  0.97548787],
       [-0.12996881,  0.73979544,  0.97548787,  1.        ]])

In [8]:
eigen_val, eigen_vectors = np.linalg.eig(cov_mat)

In [9]:
print(eigen_val)

[2.6084326  1.07278136 0.31307298 0.00571305]


In [10]:
print(eigen_vectors)

[[ 0.13660209 -0.92307013 -0.34467808  0.10236418]
 [-0.53356824  0.2159777  -0.81375057 -0.08042742]
 [-0.57488176 -0.29558368  0.36472893 -0.67015973]
 [-0.60510806 -0.11800617  0.29322317  0.73071126]]


In [11]:
n_components = 3

In [12]:
top_eigen_vectors = eigen_vectors[:, :n_components]

In [13]:
transformed_data = np.matmul(np.array(df_std), top_eigen_vectors)

In [14]:
pd.DataFrame(data=transformed_data, columns=['principal component ' + str(i+1) for i in range(n_components)])

principal component 1  principal component 2  principal component 3
0               0.137940               0.774204               0.889827
1              -2.631765              -0.742779              -0.024679
2               0.109512               1.279401              -0.502511
3               0.629107              -0.087956              -0.447421
4               1.755206              -1.222870               0.084784

-----------------------

### **Sklearn**

In [19]:
from sklearn.decomposition import PCA

pca = PCA(n_components = n_components)
principalcomponents = pca.fit_transform(df_std)
principaldf = pd.DataFrame(data=principalcomponents, columns=['principal component ' + str(i+1) for i in range(n_components)])
principaldf

principal component 1  principal component 2  principal component 3
0              -0.137940               0.774204               0.889827
1               2.631765              -0.742779              -0.024679
2              -0.109512               1.279401              -0.502511
3              -0.629107              -0.087956              -0.447421
4              -1.755206              -1.222870               0.084784

#### **Reference**

- https://www.youtube.com/watch?v=mWzoKXcA_14&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=73