<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day6_Numpy_Array_Math_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

- Array math or arithmatic can be performed very easily on NumPy arrays. For example, addition of two rank 2 arrays can be done as:

#### **Addition**

In [5]:
# Add two NumPy arrays using "+" operator
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print("Addition of A and B is :")
print(A+B)

Addition of A and B is :
[[ 8 10 12]
 [14 16 18]]


In [7]:
# Add two numpy arrays and plot the resultant graph
X = np.array([2,3])
Y = np.array([4,2])
print("Addition of A and B is :")
print(X+Y)

Addition of A and B is :
[6 5]


- Besides using **'+' operator**, we can also use the **np.add()** function to add two arrays.

In [8]:
# Add two numpy arrays using the np.add() function
# Add two NumPy arrays using "+" operator
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print("Addition of A and B is :")
print(np.add(A, B))

Addition of A and B is :
[[ 8 10 12]
 [14 16 18]]


#### **Subtraction**

In [9]:
# subtract two numpy arrays using "-" operator
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print("Subtraction of A and B is :")  # same as np.subtract(A,B)
print(A-B)

Subtraction of A and B is :
[[-6 -6 -6]
 [-6 -6 -6]]


#### **Multiplication**

In [10]:
# Multiply two numpy arrays using "*" operator
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print("Multiplication of A and B is :")  # same as np.multiply(A,B)
print(A*B)

Multiplication of A and B is :
[[ 7 16 27]
 [40 55 72]]


#### **Divide**

In [11]:
# Devide two numpy arrays using "/" operator
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print("Division of A and B is :")  # same as np.divide(A,B)
print(A/B)

Division of A and B is :
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


- What’s a practical use of the ability to multiply or divide two arrays?

- Let’s suppose we have three arrays; one containing the names of a group of people, other the corresponding heights of these individuals and the last one corresponding weights of the individuals in the group. We want to calculate the BMI of this group of people.

- The formula to calculate BMI is as follows:

 - Divide the weight in kilograms(kg) by the height in meters (m)

 - Divide the answer by the height again

- **Using the BMI, you can classify a person as healthy, overweight, or underweight using the following categories:**

  - Underweight if BMI<18.5

  - Overweight if BMI>25

  - Normal weight if 18.5 <=BMI <=25

- Using array division, we could simply calculate BMI.


In [13]:
names = np.array(['nirmal', 'priyanka', 'reshma'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 45, 59])
bmi = weights/heights **2  # calculate the BMI
print("The Body Mass Index (BMI) of nirmal, priyanka, reshma is: ", bmi)
print("overweight: ", names[bmi>25])
print("underweight: ", names[bmi<18.5])
print("healthy: ", names[(bmi>=18.5) & (bmi<=25)])

The Body Mass Index (BMI) of nirmal, priyanka, reshma is:  [28.88888889 14.20275218 23.046875  ]
overweight:  ['nirmal']
underweight:  ['priyanka']
healthy:  ['reshma']


- when we multiply two arrays, it actually means multiplying each of there corresponding elements. Very often, we want to perform a scalar or dot product. **The dot product is an algebraic operation that takes two coordinate vectors of equal size and returns a single number.** The dot product of two vectors is calculated by multiplying corresponding entries in each vector and adding up all of those products

In [14]:
x = np.array([2,3])
y = np.array([4,2])
print("The dot product of x and y is: ", np.dot(x,y))

The dot product of x and y is:  14


- Dot products also work on rank 2 arrays. If we perform a dot product of two rank 2 arrays, it is equivalant to the matrix multiplication.

In [15]:
x = np.array([[1,2,3],[4,5,6]])  # 2 * 3
y = np.array([[7,8],[9,10],[11,12]])  # 3* 2
print("The dot product of x and y is:")
print(np.dot(x,y))

The dot product of x and y is:
[[ 58  64]
 [139 154]]


### **Reference**

- https://www.youtube.com/watch?v=AO1RthUL3es&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=6