<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day7_Matrix_and_Cumulative_Sum_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#### **Matrix and Cumulative sum in NumPy Array**

- NumPy provides another class in addition to arrays(ndarray). The matrix class is a subclass of the ndarray, and it is basically identical to the ndarray with one notable exception. A matrix is strictly two-dimensional, while an ndarray cab be multidimensional. Creating a matrix object is similar creating numpy array.

In [2]:
a = np.matrix([[1,2],[4,5]])
b = np.matrix([[7,8],[2,3]])
print("The matrix a is:")
print(a)
print("The matrix b is:")
print(b)

The matrix a is:
[[1 2]
 [4 5]]
The matrix b is:
[[7 8]
 [2 3]]


#### **we can also convert a NumPy array to a matrix using the asmatrix() function**

In [3]:
a = np.matrix([[1,2],[4,5]])
b = np.matrix([[7,8],[2,3]])

c = np.asmatrix(a)
d = np.asmatrix(b)

print("The matrix c is:")
print(c)
print("The matrix d is:")
print(d)

The matrix c is:
[[1 2]
 [4 5]]
The matrix d is:
[[7 8]
 [2 3]]


- Another importance **difference** between an **ndarray and a matrix** occurs when we perform **multiplications** on them.

- When **multiplying two ndarray objects**, the result is the **element by element multiplication**.

- On the other hand when **multiplying two matrix objects**, the result is the **dot product** (equivalent to the **np.dot()** function.

In [5]:
x1 = np.array([[1,2],[4,5]])
y1 = np.array([[7,8],[2,3]])
print("The product of x1 and y1 is:")  # element by element multiplication
print(x1 * y1)

x2 = np.matrix([[1,2],[4,5]])
y2 = np.matrix([[7,8],[2,3]])
print("The product of x2 and y2 is:")  # dot product; same as np.dot()
print(x2 * y2)

The product of x1 and y1 is:
[[ 7 16]
 [ 8 15]]
The product of x2 and y2 is:
[[11 14]
 [38 47]]


- Very often, **when dealing with numerical data**, there is a need to find the **cumulative sum** of numbers in numpy array.

- We can call the **cumsum()** function to get the cumulative sum of the array elements.

In [6]:
A = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The value of array A is:")
print(A)
print("The cumulative sum of all the elements in the array is:")
print(A.cumsum())

The value of array A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The cumulative sum of all the elements in the array is:
[ 1  3  6 10 15 21 28 36 45]


- In this case, **cumsum()** function returns a **rank 1 array** containing the cumulative sum of all of the elements in the A array.

- The **cumsum()** function also takes in an **optional argument** as axis. Specifying an **axis of o** indicates that we want to get the **cumulative sum of each column**.

In [8]:
A = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The value of array A is:")
print(A)
print("The cumulative sum of all the elements in the array is:")
print(A.cumsum(axis=0))

The value of array A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The cumulative sum of all the elements in the array is:
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


- Specifying an **axis of 1** indicates that we want to get the **cumulative sum of each row**

In [9]:
A = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The value of array A is:")
print(A)
print("The cumulative sum of all the elements in the array is:")
print(A.cumsum(axis=1))

The value of array A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The cumulative sum of all the elements in the array is:
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


#### **Reference**

- https://www.youtube.com/watch?v=kq3bngOTeRk&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=7