<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day71_Scipy_special_functions_using_Python_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **Scipy Special Functions**

- scipy.special.jn()

- scipy.special.ellipj()

- scipy.special.gamma()

- scipy.special.gammaln()

- scipy.special.erf()

In [1]:
import numpy as np
from scipy import linalg

In [2]:
arr = np.array([[1,2],[3,4]])
linalg.det(arr)

# 1*4 - 2*3 = -2

-2.0

In [3]:
linalg.det(np.ones((1,2)))

ValueError: ignored

In [5]:
linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [6]:
linalg.inv(np.ones((1,2)))

ValueError: ignored

In [7]:
linalg.svd(arr)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

#### **Reference**

- https://www.youtube.com/watch?v=FOzAM9T8nlY&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=75