<a href="https://colab.research.google.com/github/sureshmecad/Samrat-Ashok-Technology-Internship/blob/main/Day9_NumPy_Array_Assignment_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

- When assigning **NumPy arrays**, we have to take note of **how arrays are assigned.**

#### **Copying Reference**

In [2]:
list = [[1,2,3],[4,5,6]]
array1 = np.array(list)
print("The value of array1 is:")
print(array1)

The value of array1 is:
[[1 2 3]
 [4 5 6]]


- When we assign **array1 to another variable, array2**, a **copy** of the **array is created**.

In [3]:
list = [[1,2,3],[4,5,6]]
array1 = np.array(list)
print("The value of array1 is:")
print(array1)
array2 = array1
print("The value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]


- However, **array2** is actually pointing to the **original array1**. So **any changes made to either array will affect the other**.

In [4]:
list = [[1,2,3],[4,5,6]]
array1 = np.array(list)
print("The value of array1 is:")
print(array1)
array2 = array1
print("The value of array2 is:")
print(array2)
array2[0][0]=11
print("The updated array2 is:")
print(array2)
print("The updated array1 is:")
print(array1)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated array2 is:
[[11  2  3]
 [ 4  5  6]]
The updated array1 is:
[[11  2  3]
 [ 4  5  6]]


- In the **"Reshaping arrays"**, we saw how to change the shape of an ndarray using the **reshape()** function.

- In addition to using reshape() function, we can also use the shape property of the ndarray to change its dimension. If **array1 changes ahape, array2 will also be affected.** 

In [5]:
list = [[1,2,3],[4,5,6]]
array1 = np.array(list)
print("The value of array1 is:")
print(array1)
array2 = array1
print("The value of array2 is:")
print(array2)
array1.shape = 1,-1
print("The updated value of array1 is:")
print(array1)
print("The updated value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated value of array1 is:
[[1 2 3 4 5 6]]
The updated value of array2 is:
[[1 2 3 4 5 6]]


#### **Copying by View (Shallow Copy)**

- NumPy has a **view() function** that allows us to **create a copy of an array** by reference, while at the same time ensuring that **changing the shape of the original array does not affect the shape of the copy**. This is known as a shallow copy.

In [6]:
list = [[1,2,3],[4,5,6]]
array1 = np.array(list)
print("The value of array1 is:")
print(array1)
array2 = array1.view()
print("The value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]


- **modify a value in array1** and we will see the **changes in array2**.

In [7]:
list = [[1,2,3],[4,5,6]]
array1 = np.array(list)
print("The value of array1 is:")
print(array1)
array2 = array1.view()
print("The value of array2 is:")
print(array2)
array1[0][0]=11
print("The updated array1 is:")
print(array1)
print("The updated array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated array1 is:
[[11  2  3]
 [ 4  5  6]]
The updated array2 is:
[[11  2  3]
 [ 4  5  6]]


- Untill now the **shallow copy** is identical to the copying performed in the previous section. But with shallow copying, when we **change the shape of array1, array2 is unaffected.**

In [8]:
list = [[1,2,3],[4,5,6]]
array1 = np.array(list)
print("The value of array1 is:")
print(array1)
array2 = array1.view()
print("The value of array2 is:")
print(array2)
array1.shape = 1,-1
print("The updated value of array1 is:")
print(array1)
print("The updated value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated value of array1 is:
[[1 2 3 4 5 6]]
The updated value of array2 is:
[[1 2 3]
 [4 5 6]]


#### **Copying by Value (Deep Copy)**

- If you want to copy an array by value, use the **copy()** function.

In [10]:
list = [[1,2,3,4],[5,6,7,8]]
array1 = np.array(list)
array2 = array1.copy()
print("The value of array1 is:")
print(array1)
print("The value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3 4]
 [5 6 7 8]]
The value of array2 is:
[[1 2 3 4]
 [5 6 7 8]]


- The **copy()** function creates a **deep copy of the array** -- it creates a complete copy of the array and its data. When you assign the **copy of the array to another variable**, any **changes** made to the **shape** of the original array **will not affect** its copy.

In [11]:
list = [[1,2,3],[4,5,6]]
array1 = np.array(list)
print("The value of array1 is:")
print(array1)
array2 = array1.copy()
print("The value of array2 is:")
print(array2)
array1[0][0]=11
print("The updated array1 is:")
print(array1)
print("The updated array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated array1 is:
[[11  2  3]
 [ 4  5  6]]
The updated array2 is:
[[1 2 3]
 [4 5 6]]


In [12]:
list = [[1,2,3],[4,5,6]]
array1 = np.array(list)
print("The value of array1 is:")
print(array1)
array2 = array1.copy()
print("The value of array2 is:")
print(array2)
array1.shape = 1,-1
print("The updated value of array1 is:")
print(array1)
print("The updated value of array2 is:")
print(array2)

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated value of array1 is:
[[1 2 3 4 5 6]]
The updated value of array2 is:
[[1 2 3]
 [4 5 6]]


#### **Reference**

- https://www.youtube.com/watch?v=dFBkrfj3QdY&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=9